airbnb:
  outputs:
    dev:
      account: tycibvq-xab15771 
      database: VANTAGEDW
      password: QAWS123qaws4102!
      role: ITC_ADMIN
      schema: VANTAGE
      threads: 4
      type: snowflake
      user: MEETNANU
      warehouse: PROCESSING_WH
  target: dev
dbt_hol:
  outputs:
    dev:
      account: XZNFSCV-QHB34722 
      database: TESTDB
      password: QAWS123qaws!
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 2
      type: snowflake
      user: MEETNANU
      warehouse: COMPUTE_WH
  target: dev

#accountname =hhvqkhk-gbb36396  #ORGANIZATION-ACCOUNTNAME
##region = AWS_US_EAST_1
#username = meetnanu
#password = QAWS123qaws
#dbname= TESTDB
#schemaname = PUBLIC
#warehousename = COMPUTE_WH
